### ISSUE TITLE
0.5.0 release checklist

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#528]
* [x] Fix all rustc warnings
 * [x] Make sure all unit tests pass
 * [x] Test all examples
 * [x] Read all examples, clean up anything Not Good Enough.
 * [x] Read all docs (ideally in rendered form)
 * [x] Make sure website is updated and in-sync
 * [x] rustfmt
 * [x] clippy
 * [x] Search for and remove all `expect()` and `unwrap()` calls
 * [x] Search for and address all `TODO` and `BUGGO` comments
 * [x] Make sure readme is updated (should be the same as the top-level crate docs)
 * [x] Make sure changelog is up to date, ideally including full links to issues or commits (not just github issue numbers)
 * [x] ~~Clean up and release [ggez-goodies](https://github.com/ggez/ggez-goodies/issues/10) as well.~~

Things still to consider:

 * ~~Look at the comments for `audio::Source` and see if anything can be made better, but don't be afraid to push it off until later.~~ Later
 * Consider handling ~~#464~~ , ~~#529~~ Done
 * ~~Either make `DrawTransform` a real thing, ditch it entirely (including from docs!), or just make an easy and public way to turn a `DrawParam` into a matrix.~~ Done

**Comment by icefoxen** [comment]
We should slap whatever the hide-this-from-rustdoc annotation is on various things, such as the `FooGeneric` types.

**Comment by icefoxen** [comment]
Okay let's actually heckin' do this.  Main blockers:

 * Ensure text metric functions work -- #569
 * Keyboard and gamepad API cleanup -- #404 
 * Whatever is necessary to make shadow example work
 * Website :F

**Comment by icefoxen** [comment]
Released July 20, 2019
