### ISSUE TITLE
0.6.0 release checklist

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#697]
I think I'm going to make this a bugfix-and-update release, focusing on upgrading to winit 0.20... once that ever gets released.

Things that should get done:

 * [x] ~~Upgrade to winit 0.20.  `glutin` 0.21 makes some really annoying API changes, unfortunately, so I'm currently trying to avoid it... not sure how feasible that will be in the long run though.~~ -- ~~Can't be done without updating `gfx_window_glutin`, which uses winit 0.19 and hasn't had a new release.  We could try to make a `gfx_window_glutin` update, or we could vendor it all since it's pretty small and update it that way, or we could just leave it as it is and deal with old, somewhat-buggy winit 0.19.~~  Done in #837 , thanks to sapir and imbris for making this possible!
 * [x] Remove `nalgebra` in favor of ~~`euclid`~~ `glam`, if possible.  Lyon already uses `euclid`, so in THEORY, using only `euclid` will make compile times faster.  ...In practice, so far, `rodio` 0.9 uses `nalgebra` anyway, and the current git master of it removes `nalgebra` but adds `failure` which more than eats up the gained compile time.  I just can't win.  Let's just use `glam` which at least only takes half a second to compile.
 * [x] Remove rand from examples in favor of `oorandom` or something similarly minimal
 * [ ] Maybe try to make `gilrs` a little less of a pain
 * [x] Version bump rodio
 * ~~Go through the audio API and consistent-ify it with the new rodio.  Might need a total rewrite but it's relatively small, and should make things simpler since the new rodio API looks a bit better-organized than the old one.~~ I really can't handle a full rewrite right now.
 * [x] Version bump glyph_brush
 * [x] Version bump lyon
 * [x] Version bump whatever else presents itself

...In light of the `glutin` thing I'm really not sure this is worth the trouble.  Maybe just stick with the current version of `glutin`, fix everything else, then call it 1.0.  Meh.  We should try to make a big pile of bugfixes anyway though.

**Comment by alexheretic** [comment]
If you're still aiming to use pre-ll gfx I'm moving Robo Instructus to [alexheretic/old-school-gfx-glutin-ext](https://github.com/alexheretic/old-school-gfx-glutin-ext) _(replaces gfx_window_glutin)_ which is much easier for me to keep up to date with glutin.

**Comment by icefoxen** [comment]
Thanks for the tip!  Plans are still kinda mutating a bit though.  I think there's going to be a "bugfixes and such" 0.5.2 release, and then 0.6 or whatever it ends up being will be when the `glow` graphics backend, `winit` 0.20 and such hit.  That's my feeling right now at least.

**Comment by hugovdm** [comment]
I'm hoping the next release will also switch to a newer rodio, if that's available... I want to use CPAL 0.12 on Linux, but rodio 0.11 depends on CPAL 0.11, causing version conflicts for the alsa "native library". (rodio at HEAD uses CPAL 0.12 now, but I have no idea when there will be an actual release for that.)

**Comment by AaronM04** [comment]
I'm also pretty excited about using the latest rodio, mainly because I'm trying to get ggez working on OpenBSD and to do that I need to add [sndio](https://sndio.org/) support to cpal. [I've already done the hard work here -- it just needs a few improvements before it's ready for a PR](https://github.com/conwayste/cpal/tree/aaron/openbsd_ggez_DELETE_ASIO)

**Comment by icefoxen** [comment]
My new new goal is to try to get this out by the end of 2020, which seems more feasible than making the `ggraphics` branch mainline for now.  This will definitely have breaking changes, but should be an overall improvement.  Hopefully can fix a bevy of bugs too.  Updating the checklist to reflect that.

**Comment by icefoxen** [comment]
# Things that maintainers should do prior to every release!

 * [ ] Note that updating a dep to a breaking version (i.e., nalgebra 0.13 -> 0.14) is a BREAKING
API CHANGE and should not be done on things that don't break API.  For instance, we screwed this
up 'cause ggez 0.4.0 used nalgebra 0.13 and 0.4.1 used nalgebra 0.14... so this broke the exposed
API.  (Doing this for packages that aren't publically exposed is PROBABLY okay...)
 * [ ] Fix all rustc warnings
 * [ ] Make sure all unit tests pass
 * [ ] Test all examples
 * [ ] Read all docs (ideally in rendered form)
 * [ ] Make sure website is updated and in-sync
 * [ ] rustfmt
 * [ ] clippy
 * [ ] Search for and remove all `expect()` and `unwrap()` calls
 * [ ] Search for and address all `TODO` and `BUGGO` comments
 * [ ] Make sure readme is updated (should be the same as the top-level crate docs)
 * [ ] Make sure changelog is up to date, ideally including full links to issues or commits (not just github issue numbers)

**Comment by icefoxen** [comment]
Basically the last thing to do is address the heckin' TODO comment in `src/graphics/mesh.rs`, but that involves version-bumping Lyon, which has gone through a big change...

**Comment by IGBC** [comment]
why did you remove nalgebra?

**Comment by Andy-Python-Programmer** [comment]
> why did you remove nalgebra?

Pretty good question.

**Comment by icefoxen** [comment]
@IGBC Compile times, complexity, unstable API...  basically it was overkill for what ggez needed internally, and having the public API use entirely `mint`'s types means a user can use `nalgebra` in their games anyway.  Re-exporting a particular version of `nalgebra` was also bad because it meant that when `nalgebra` updated and ggez didn't, people got confused by the incompatibility.

@PSteinhaus @nobbele You guys have gotten a big pile of outstanding issues fixed in the last couple weeks...  Do you feel it's ready for us to start making a 0.6.0-rc2 release, or are there other things you want to take care of first?

Potential outstanding PR's we might want to resolve first:

 * #943 
 * #905 
 * Anything left in https://github.com/ggez/ggez/milestone/6 that really makes us say "yes please" or "ooh that would be neat".  Personally there's nothing there that sparks joy in my heart, so I'm fine releasing 0.6.0 with those issues still open.

**Comment by nobbele** [comment]
#800 should be fixed first I think

**Comment by PSteinhaus** [comment]
> Personally there's nothing there that sparks joy in my heart, so I'm fine releasing 0.6.0 with those issues still open.

Neither do I feel "joy in my heart" looking at them ^^
But I think @nobbele is right and we should decide how to solve #800 first, because it's probably the only issue left that might result in a slight API change.

**Comment by nobbele** [comment]
Ignore my #800 request, it was something else.

**Comment by IGBC** [comment]
I request #813 be promoted to a 0.6 Blocker.

What started as a simple "check we didn't already fix that" has turned into a full regression hunt in the canvas subsystem. 

Somewhere in the devel branch we have introduced a bug that prevents drawing to a canvas without calling `present` afterwards, which is causing problems for applications which use that technique for image post-processing.

**Comment by IGBC** [comment]
@icefoxen you can tick off #905

**Comment by nobbele** [comment]
Everything has been resolved now, should we make an rc2 then?

**Comment by PSteinhaus** [comment]
We could. But since #805 is a very minor thing (IMO) I'm tempted to just fully release 0.6.0, once we did the final touches concerning #800 maybe. Or is there anything left for 0.6.0 that I'm missing?

**Comment by icefoxen** [comment]
Nope, don't think so.  I'm pretty happy with where we are for a 0.6.0 release.

**Comment by icefoxen** [comment]
Welp, 0.6.0-rc2 has been out for almost a couple weeks and nothing terrible has happened, so I think it's time to just call it 0.6.0.

**Comment by PSteinhaus** [comment]
Technically, a memory leak was discovered and fixed, but that was way older than 0.6.0-rc2, so I think we can safely call devel 0.6.0 now.
